apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fjezn68h5-python-gitops
  description: This is GitOps manifest for fjezn68h5-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=fjezn68h5-python
    backstage.io/kubernetes-id: fjezn68h5-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: fjezn68h5-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fjezn68h5-python
