apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fjezn68h5-python
  janus-idp.io/tekton: fjezn68h5-python
  backstage.io/kubernetes-id: fjezn68h5-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fjezn68h5-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
